### ISSUE TITLE
Desecrator with wine on linux not working : no terrorized zone produced

### ISSUE THREAD

**Issue by DrLoiseau** [Karyoplasma/LoD-Desecrator#1]
Hey,

I have trouble making desecrator work on linux with diablo 2 running through wine. 

I have properly put the Data folder in the D2 install folder, added the -direct -txt arguments to the param field in the LAUNCHING section of Plugy.ini.

I had to adapt a little the TerrorZoneHandler.java file to replace windows backslashes in the paths with regular slashes (linux paths use slash instead of backslash so the files couldn't be found). With these modifications the .jar file seems to work ok, I can set the Excel location, select the zone I want to terrorize and the button turns green. However in game (hell difficulty) the zone is not terrorized, there are only regular monsters without the  desecrated suffix.

Any idea what could go wrong ?
Thanks !

**Comment by Karyoplasma** [comment]
Easiest way to check if the program actually did something by terrorizing Blood Moor. Open monstats.txt and look at the zombie1 line, it should start with
 `zombie1	5	zombie1	zombie2	0	ZombieTerror`
If it's the regular namestring, the program did not do anything, but I wouldn't really know why from the top of my head. If there is any read/write issue (like incorrect paths or no access), the status indicator won't turn green (I added that specifically just so that the program doesn't silently fail). It only turns green if the TZ has been applied and the file writing was successful, if there is a nullpointer it would stay gray (fixed with latest push, red now) and if there is an I/O exception it would turn red. 

But good call with the backslashes, I thought the Path class is smart enough to resolve that on its own but apparently not. I tested it and forward slashes work on Windows as well, so gonna change that. Thanks for the heads-up.

**Comment by DrLoiseau** [comment]
Hey, thanks for tip and for the compatibility with linux, that's great !

The program works fine, the monsters stats are modified according to the zone I set. 

I think there was a problem as my PlugY.exe was in a PlugY folder in the diablo 2 install folder. I moved it directly to the base folder, and now the game crashes when I enter a game. I tried to make a new character but it crashes too. It works fine when I remove the data folder and the parameters to the plugy.ini. Not sure I'm going to be able to play with terror zones...

**Comment by Karyoplasma** [comment]
The PlugY folder has another folder called PlugY. If you move the .exe into the main install folder, you have to put all the files in PlugY/PlugY (should be 11 or so) into just PlugY. If they are missing, it will crash on load.
Not sure why it doesn't crash when you remove -direct -txt. One of the PlugY/PlugY files is a .txt tho (something related to the new character stat page I think), so maybe removing that will fix the issue of the missing .txt. It would still cause issues when you open the stash tho (missing buttons, or crash - not sure how D2 handles missing dc6 files).

Alternatively, you could put the Data folder into the PlugY folder, that should work as well.

**Comment by DrLoiseau** [comment]
Sorry I wasn't precise enough, I had two folders : the PlugY/ you mentioned with 11 files, and a Mod PlugY/ folder. I moved the .exe and .ini and other files to d2 main folder, I didn't touch the PlugY/ folder.
If I move both the Data/ folder and the Plugy.exe to the PlugY folder the game still crashes. The BlizzardError files are not informative, there might be a conflict with the .txt files but I have no clue how to fix it.

Thanks for your help anyway !

**Comment by Anonimous-1690** [comment]
> Hi bro, please help me convert this mod to Diablo 2 lod

[Rune Easy Upgrade-217-1-2-1708447033.zip](https://github.com/user-attachments/files/23374597/Rune.Easy.Upgrade-217-1-2-1708447033.zip)

**Comment by Anonimous-1690** [comment]
Каріоплазма підор
